name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: bash    
    
    steps:

          
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: webui-dev/webui.git
        path: .
        ref: main
          
       
    - name: build
      run: |
            $env:PATH = "C:\msys64\usr\bin;$env:PATH"
            pacman -S mingw-w64-i686-toolchain
